name: CICD Whistle Alliance 
run-name: ${{ github.actor }} is running Build and deploy 🚀
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t holudarey/whistle_alliance .
      - name: Publish image to Docker Hub
        run: docker push holudarey/whistle_alliance:latest
  deploy:
    needs: build
    runs-on: [whistle_alliance] 
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull holudarey/whistle_alliance:latest
      - name: Deleting Old Container
        run: docker rm -f whistle_alliance-container
      - name: Run docker container 
        run: docker run -d -p  443:443 --name whistle_alliance-container holudarey/whistle_alliance
